# ----
# Site

title: Staging Docs
description: Staging Docs
url: http://mythz.servicestack.net/staging/
repository: mythz/staging
google_analytics_key: 

collections:
  documentation:
    title: Documentation
    output: true
    permalink: /:slug.html
gems:
  - github-pages

exclude:
  - README.md
  - LICENCE

topics: []
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      collection: documentation
    values:
      priority: 999
  -
    scope:
      collection: releases
    values:
      layout: default

# -----
# Build
sass:
  sass_dir: _scss
  style: :compressed